### ISSUE TITLE
Why not use filter hooks for adjusting the markup of media credits?

### ISSUE THREAD

**Issue by mundschenk-at** [phillipian/phillipian-wp-2019#33]
While you are of course free to fork the Media Credit plugin, from looking at the code I'm not quite sure why see a need to do that: There are filter hooks that allow a theme to completely replace the markup with custom HTML. 

(If there's anything that that currently cannot be done, I'll gladly add additional hooks.)

**Comment by wwsalmon** [comment]
Oh hey -- I'm relatively new to Wordpress development, how would I go about doing that? The changes I've made are to author-media.php and media-credit-shortcode.php.

The author-media changes are minor, with the only real change being setting the pulled image side to "large" rather than "thumbnail", and class names changed around for convenience. Is there a way to specify image size for author pages currently?

I rewrote media-credit-shortcode based on the markup we had been using -- we were originally planning to stop using the plugin and I wrote a shortcode override to make sure legacy shortcodes were still getting processed; this was the code I copied into the fork. I had written an override for the [caption] shortcode too, which is reflected in the plugin fork's shortcode code. Is there a way to achieve the same thing using the original plugin?

Thanks!

**Comment by mundschenk-at** [comment]
Hi @wwsalmon:

- You can override the output of the `[media-cedit]` shortcode by filtering [`media_credit_shortcode`](https://github.com/mundschenk-at/media-credit/blob/master/includes/media-credit/components/class-shortcodes.php#L261).
- Not sure what you intend with the `[caption]` shortcode (it's not in the fork apparently), but if it is to always add media credits even without the shortcode being present, I can dig out some example code from my website's custom theme which does exactly that.
- As for the "author media" markup, there is no currently no parameter for `Media_Credit::display_author_media()` to set the image size. However, you can simply use [`Media_Credit::author_media_and_posts()`](https://github.com/mundschenk-at/media-credit/blob/master/includes/class-media-credit.php#L208) instead to fetch the attachments and display them in whatever way you choose.

**Comment by wwsalmon** [comment]
@mundschenk-at thanks for the pointers! I've written a function [`custom_media_credit` in `functions.php`](https://github.com/phillipian/phillipian-wp-2019/blob/master/functions.php#L7) and added `add_filter('media_credit_shortcode', 'custom_media_credit'),` but am unable to get `$content` containing the actual image in the post body to go through. I've tried including `$content` as a function argument but get the error "Too few arguments to function custom_media_credit()". How would I get it working?

**Comment by mundschenk-at** [comment]
Your filter function's arguments must match the filter's (and not the containing shortcode method!). Also, if the function has more than 3 arguments, you must include the argument number in the call to `add_filter()`. As for replacing the  shortcode entirely, that's of course also a possibility, but in this case it bypasses the attribute sanitization and is thus more complicated to implement properly.

Regarding the Classic Editor: No, unfortunately that's all a JavaScript thing. In the long run, the classic editor integration will probably be removed as there is no stable and documented API for interacting with TinyMCE in WordPress. I'll look into the issue, but I can't promise much for this part of the plugin. What you are seeing is the temporary markup for display within TinyMCE, which should be converted by to shortcodes on saving. Do you have any JavaScript errors in the browser console when this happens?

**Comment by wwsalmon** [comment]
@mundschenk-at Got it! I've gotten it working how we want it to now, thanks so much for your help!
